# Makefile

all: interpretador acrescentaOrigemDestino apagaFicheiro contaFicheiro copiaFicheiro informaFicheiro listaDiretoria mostraFicheiro

interpretador: interpretador.c	 
	gcc interpretador.c -o int
	
acrescentaOrigemDestino: acrescentaOrigemDestino.c
	gcc acrescentaOrigemDestino.c -o acrescenta

apagaFicheiro: apagaFicheiro.c
	gcc apagaFicheiro.c -o apaga

contaFicheiro: contaFicheiro.c
	gcc contaFicheiro.c -o conta

copiaFicheiro: copiaFicheiro.c
	gcc copiaFicheiro.c -o copia

informaFicheiro: informaFicheiro.c
	gcc informaFicheiro.c -o informa
	
listaDiretoria: listaDiretoria.c
	gcc listaDiretoria.c -o lista
	
mostraFicheiro: mostraFicheiro.c
	gcc mostraFicheiro.c -o mostra

